baseurl = "/"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "terminal"
pagination.pagerSize = 5

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = true # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "amruthn.com"

    [languages.en.params]
      subtitle = "amruth niranjan's portfolio page"
      owner = "amruth niranjan"
      keywords = "portfolio"
      copyright = "2025"
      menuMore = "show more"
      readMore = "read more"
      readOtherPosts = "read other posts"
      newerPosts = "newer posts"
      olderPosts = "older posts"
      missingContentMessage = "page not found..."
      missingBackButtonLabel = "back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "amruthn.com"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "projects"
          name = "projects"
          url = "/projects"
          weight = 1
          
        [[languages.en.menu.main]]
          identifier = "micro"
          name = "micro"
          url = "/projects/micro"
          parent = "projects"
          weight = 1
          
        # Micro projects
        [[languages.en.menu.main]]
          identifier = "auto-commit"
          name = "auto commits"
          url = "/projects/auto-commit"
          parent = "micro"
          weight = 1
          
        [[languages.en.menu.main]]
          identifier = "auto-email"
          name = "auto email"
          url = "/projects/auto-email"
          parent = "micro"
          weight = 2
          
        [[languages.en.menu.main]]
          identifier = "platecalc"
          name = "plate calc"
          url = "/projects/platecalc"
          parent = "micro"
          weight = 3
          
        [[languages.en.menu.main]]
          identifier = "minor"
          name = "minor"
          url = "/projects/minor"
          parent = "projects"
          weight = 2
          
        # Minor projects
        [[languages.en.menu.main]]
          identifier = "file_system"
          name = "file system"
          url = "/projects/file_system"
          parent = "minor"
          weight = 1
          
        [[languages.en.menu.main]]
          identifier = "portfolio"
          name = "portfolio"
          url = "/projects/portfolio"
          parent = "minor"
          weight = 2
          
        [[languages.en.menu.main]]
          identifier = "pthreads"
          name = "pthreads"
          url = "/projects/pthreads"
          parent = "minor"
          weight = 3
          
        [[languages.en.menu.main]]
          identifier = "shell"
          name = "shell"
          url = "/projects/shell"
          parent = "minor"
          weight = 4
          
        [[languages.en.menu.main]]
          identifier = "major"
          name = "major"
          url = "/projects/major"
          parent = "projects"
          weight = 3
          
        # Major projects
        [[languages.en.menu.main]]
          identifier = "roomform"
          name = "roomform"
          url = "/projects/roomform"
          parent = "major"
          weight = 1
          
        [[languages.en.menu.main]]
          identifier = "deepsoz-hem"
          name = "deepsoz-hem"
          url = "/projects/deepsoz-hem"
          parent = "major"
          weight = 2
          
        [[languages.en.menu.main]]
          identifier = "rightup"
          name = "rightup"
          url = "/projects/rightup"
          parent = "major"
          weight = 3

        [[languages.en.menu.main]]
          identifier = "snowpilot"
          name = "snowpilot"
          url = "/projects/snowpilot"
          parent = "major"
          weight = 4
          
        [[languages.en.menu.main]]
          identifier = "other"
          name = "other"
          url = "/other"
          weight = 2
          
        [[languages.en.menu.main]]
          identifier = "fitness"
          name = "fitness"
          url = "/other/fitness"
          parent = "other"
          weight = 1
          
        [[languages.en.menu.main]]
          identifier = "media"
          name = "media"
          url = "/other/media"
          parent = "other"
          weight = 2

[module]
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  # replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
# [[module.imports]]
  # path = 'github.com/panr/hugo-theme-terminal/v4'